name: Deploy dev
env:
  CURRENT_ENV: develop
  AWS_LOGIN: ${{ secrets.AWS_ACCOUNT_EMAIL }}
on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - feature/**
jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml