name: Deploy
on:
  workflow_call
jobs:
  eslint:
    strategy:
      matrix:
        node-versions: [16, 18, 20]
        operating-systems: [ubuntu-20.04, windows-2019]
    runs-on: ${{ matrix.operating-systems }}
    steps:
      - name: Get code
        uses: actions/checkout@v4
        with:
          node-version: ${{ matrix.node-versions }}
      - name: Cache project
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .nuxt
          key: npm-deps-${{ needs.build-upload.outputs.commit-id }}
      - name: Install node packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build app
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm run build
      - name: Run eslint
        id: run-eslint
        run: ls && npm run lint
  unit-tests:
    strategy:
      matrix:
        operating-systems: [ubuntu-20.04, windows-2019]
    runs-on: ${{ matrix.operating-systems }}
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache project
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .nuxt
          key: npm-deps-${{ needs.build-upload.outputs.commit-id }}
      - name: Install node packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build app
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm run build
      - name: Run vitest
        id: vitest
        run: ls && npm run test
      - name: Upload unit test report
        if: ${{ failure() && steps.vitest.conclusion == 'failure' }}
        uses: actions/upload-artifact@v4
        with:
          name: vitest-report
          path: ./vitest-report.json
  build-upload:
    runs-on: ${{ matrix.operating-systems }}
    needs: unit-tests
    outputs:
      commit-id: ${{ github.event.head_commit.id }}
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache project
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .nuxt
          key: npm-deps-${{ needs.build-upload.outputs.commit-id }}
      - name: Install node packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build app
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm run build
      - name: Print infos
        run: echo "${{ toJSON(github.event) }}"
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: nil-richert-fr-build-${{ env.CURRENT_ENV }}-${{ github.event.head_commit.id }}
          path: output
  echo-commit-id:
    runs-on: ubuntu-20.04
    needs: build-upload
    steps:
      - name: Display infos, list file
        run: echo "branch - $CURRENT_ENV | commitId - ${{ needs.build-upload.outputs.commit-id }} user - $GITHUB_ACTOR"
  report:
    runs-on: ubuntu-20.04
    needs: ['eslint', 'unit-tests', 'build-upload', 'echo-commit-id']
    if: ${{ always() || success() || cancelled() }}
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache project
        id: cache
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .nuxt
          key: npm-deps-${{ needs.build-upload.outputs.commit-id }}
      - name: Install node packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Build app
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm run build
      - name: Always executed
        run: echo "Job ended, listing files" && ls
  
