name: Deploy dev
on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - feature/*
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install node packages
        run: npm ci
      - name: Run eslint
        run: npm run lint
  unit-test:
    runs-on: ubuntu-latest
    needs: eslint
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install node packages
        run: npm ci
      - name: Run vitest
        run: npm run test
  build-upload:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install node packages
        run: npm ci
      - name: Build app
        run: npm run build
      - name: List files build
        run: ls
      - name: Echo event
        run: echo "${{ toJSON(github.event.head_commit) }}"
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: nil-richert-fr-build-${{ github.event.head_commit.timestamp }}-${{ github.event.head_commit.id }}
          path: output
