name: Info
on: 
  workflow_call:
    inputs:
      message:
        description: What you want
        required: false
        default: Coucou
        type: string
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Github infos
        run: echo "${{ toJSON(github) }}"
      - name: Message ko 
        if: inputs.message == 'I get knock down'
        run: echo "But i can get up again"
      # - name: Message ok 
      #   if: inputs.message != 'I get knock down'
      #   run: echo "Next lyrics are not '${{ github.events.inputs.message }}'"
