name: Lint Test
on: [push, workflow_dispatch]
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install node packages
        run: npm ci
      - name: Run eslint
        run: npm run lint
  unit-test:
    runs-on: ubuntu-latest
    needs: eslint
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install node packages
        run: npm ci
      - name: Run vitest
        run: npm run test

