name: reuse
on: workflow_call
jobs:
  dependencies-caching:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: npm-deps-${{ hashFiles('**/package.json') }}
      - name: Install node packages
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci